## What is TF-IDF? 
Term Frequency - Inverse Document Frequency (TF-IDF) is a widely used statistical method in natural language processing and information retrieval. It measures how important a term is within a document relative to a collection of documents (i.e., relative to a corpus).

Words within a text document are transformed into importance numbers by a text vectorization process. There are many different text vectorization scoring schemes, with TF-IDF being one of the most common.

As its name implies, TF-IDF vectorizes/scores a word by multiplying the word’s Term Frequency (TF) with the Inverse Document Frequency (IDF).

#### Term Frequency: 
TF of a term or word is the number of times the term appears in a document compared to the total number of words in the document.

$$
TF = \frac{\text{number of times the term appears in the document}}{\text{total number of terms in the document}}
$$

#### Inverse Document Frequency:
IDF of a term reflects the proportion of documents in the corpus that contain the term. Words unique to a small percentage of documents (e.g., technical jargon terms) receive higher importance values than words common across all documents (e.g., a, the, and).

$$
IDF = \log\left(\frac{\text{number of documents in the corpus}}{\text{number of documents in the corpus that contain the term}}\right)
$$

The TF-IDF of a term is calculated by multiplying TF and IDF scores.

$$
\text{TF-IDF} = TF \times IDF
$$

Translated into plain English, importance of a term is high when it occurs a lot in a given document and rarely in others. In short, commonality within a document measured by TF is balanced by rarity between documents measured by IDF. The resulting TF-IDF score reflects the importance of a term for a document in the corpus.

TF-IDF is useful in many natural language processing applications. For example, Search Engines use TF-IDF to rank the relevance of a document for a query. TF-IDF is also employed in text classification, text summarization, and topic modeling.

Note that there are some different approaches to calculating the IDF score. The base 10 logarithm is often used in the calculation. However, some libraries use a natural logarithm. In addition, one can be added to the denominator as follows in order to avoid division by zero.

$$
IDF = \log\left(\frac{\text{number of documents in the corpus}}{\text{number of documents in the corpus that contain the term} + 1}\right)
$$

## Numerical Example 
Imagine the term t appears 20 times in a document that contains a total of 100 words. Term Frequency (TF) of t can be calculated as 20/100 = 0.2 

Assume a collection of related documents contains 10,000 documents. If 100 documents out of 10,000 documents contain the term t , Inverse Document Frequency (IDF) of t can be calculated as log(10000/100) = 2 

Using these two quantities, we can calculate TF-IDF score of the term t for the document: 0.2*2=4

## Implementation

In [20]:
import pandas as pd
import numpy as np
corpus = ['computer science is one of the most important fields of science',
          'this course can take away many lives and destroy the world',
          'data scientists analyze data which they themselves do not understand later',
          'data science is the most important field of study',]

In [21]:
words_set = set()

for doc in  corpus:
    words = doc.split(' ')
    words_set = words_set.union(set(words))
    
print('Number of words in the corpus:',len(words_set))
print('The words in the corpus: \n', words_set)

Number of words in the corpus: 31
The words in the corpus:
 {'of', 'analyze', 'study', 'do', 'most', 'this', 'fields', 'away', 'one', 'lives', 'which', 'can', 'course', 'understand', 'the', 'computer', 'themselves', 'they', 'many', 'important', 'later', 'science', 'destroy', 'is', 'and', 'take', 'data', 'field', 'not', 'world', 'scientists'}

In [22]:
n_docs = len(corpus)         # Number of documents in the corpus
n_words_list = list(words_set) # Convert the set of unique words to a list

df_tf = pd.DataFrame(np.zeros((n_docs, len(n_words_list))), columns=n_words_list)

# Compute Term Frequency (TF)
for i in range(n_docs):
    words = corpus[i].split(' ') # Words in the document
    for w in words:
        if w in df_tf.columns:  # Ensure the word exists in the DataFrame's columns
            df_tf[w][i] += 1 / len(words)
        
df_tf

,of,analyze,study,do,most,this,fields,away,one,lives,...,science,destroy,is,and,take,data,field,not,world,scientists
0,0.181818,0.000000,0.000000,0.000000,0.090909,0.000000,0.090909,0.000000,0.090909,0.000000,...,0.181818,0.000000,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.090909,0.000000,0.090909,0.000000,0.090909,...,0.000000,0.090909,0.000000,0.090909,0.090909,0.000000,0.000000,0.000000,0.090909,0.000000
2,0.000000,0.090909,0.000000,0.090909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.181818,0.000000,0.090909,0.000000,0.090909
3,0.111111,0.000000,0.111111,0.000000,0.111111,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.111111,0.000000,0.111111,0.000000,0.000000,0.111111,0.111111,0.000000,0.000000,0.000000

The dataframe above shows we have a column for each word and a row for each document. This shows the frequency of each word in each document.

#### Counting IDF:

In [23]:
print("IDF of: ")

idf = {}

for w in words_set:
    k = 0    # number of documents in the corpus that contain this word
    
    for i in range(n_docs):
        if w in corpus[i].split():
            k += 1
            
    idf[w] =  np.log10(n_docs / k)
    
    print(f'{w:>15}: {idf[w]:>10}' )

IDF of:
             of: 0.3010299956639812
        analyze: 0.6020599913279624
          study: 0.6020599913279624
             do: 0.6020599913279624
           most: 0.3010299956639812
           this: 0.6020599913279624
         fields: 0.6020599913279624
           away: 0.6020599913279624
            one: 0.6020599913279624
          lives: 0.6020599913279624
          which: 0.6020599913279624
            can: 0.6020599913279624
         course: 0.6020599913279624
     understand: 0.6020599913279624
            the: 0.12493873660829993
       computer: 0.6020599913279624
     themselves: 0.6020599913279624
           they: 0.6020599913279624
           many: 0.6020599913279624
      important: 0.3010299956639812
          later: 0.6020599913279624
        science: 0.3010299956639812
        destroy: 0.6020599913279624
             is: 0.3010299956639812
            and: 0.6020599913279624
           take: 0.6020599913279624
           data: 0.3010299956639812
          field: 0.6020599913279624
            not: 0.6020599913279624
          world: 0.6020599913279624
     scientists: 0.6020599913279624

In [24]:
df_tf_idf = df_tf.copy()

for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * idf[w]
        
df_tf_idf

,of,analyze,study,do,most,this,fields,away,one,lives,...,science,destroy,is,and,take,data,field,not,world,scientists
0,0.054733,0.000000,0.000000,0.000000,0.027366,0.000000,0.054733,0.000000,0.054733,0.000000,...,0.054733,0.000000,0.027366,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.054733,0.000000,0.054733,0.000000,0.054733,...,0.000000,0.054733,0.000000,0.054733,0.054733,0.000000,0.000000,0.000000,0.054733,0.000000
2,0.000000,0.054733,0.000000,0.054733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.054733,0.000000,0.054733,0.000000,0.054733
3,0.033448,0.000000,0.066896,0.000000,0.033448,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033448,0.000000,0.033448,0.000000,0.000000,0.033448,0.066896,0.000000,0.000000,0.000000

## TF-IDF Using scikit-learn

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
#We need to instantiate the class first, then we can call the fit_transform method on our test corpus. This will perform all of the calculations we performed above.
tr_idf_model  = TfidfVectorizer()
tf_idf_vector = tr_idf_model.fit_transform(corpus)
#After vectorizing the corpus by the function, a sparse matrix is obtained.
print(type(tf_idf_vector), tf_idf_vector.shape)

<class 'scipy.sparse._csr.csr_matrix'> (4, 31)

In [26]:
#And we can convert to an regular array to get a better idea of the values
tf_idf_array = tf_idf_vector.toarray()

print(tf_idf_array)

[[0.         0.         0.         0.         0.31242481 0.
  0.         0.         0.         0.         0.31242481 0.24631931
  0.24631931 0.         0.         0.         0.24631931 0.
  0.49263861 0.31242481 0.49263861 0.         0.         0.
  0.19941671 0.         0.         0.         0.         0.
  0.        ]
 [0.         0.30997642 0.30997642 0.30997642 0.         0.30997642
  0.         0.30997642 0.         0.         0.         0.
  0.         0.         0.30997642 0.30997642 0.         0.
  0.         0.         0.         0.         0.         0.30997642
  0.19785393 0.         0.         0.30997642 0.         0.
  0.30997642]
 [0.29505881 0.         0.         0.         0.         0.
  0.46525551 0.         0.29505881 0.         0.         0.
  0.         0.29505881 0.         0.         0.         0.29505881
  0.         0.         0.         0.29505881 0.         0.
  0.         0.29505881 0.29505881 0.         0.29505881 0.29505881
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.31825561 0.         0.         0.40366689 0.         0.31825561
  0.31825561 0.         0.         0.         0.31825561 0.
  0.31825561 0.         0.31825561 0.         0.40366689 0.
  0.25765535 0.         0.         0.         0.         0.
  0.        ]]

In [27]:
words_set = tr_idf_model.get_feature_names_out()

print(words_set)

['analyze' 'and' 'away' 'can' 'computer' 'course' 'data' 'destroy' 'do'
 'field' 'fields' 'important' 'is' 'later' 'lives' 'many' 'most' 'not'
 'of' 'one' 'science' 'scientists' 'study' 'take' 'the' 'themselves'
 'they' 'this' 'understand' 'which' 'world']

In [28]:
df_tf_idf = pd.DataFrame(tf_idf_array, columns = words_set)

df_tf_idf

,analyze,and,away,can,computer,course,data,destroy,do,field,...,scientists,study,take,the,themselves,they,this,understand,which,world
0,0.000000,0.000000,0.000000,0.000000,0.312425,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.199417,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.309976,0.309976,0.309976,0.000000,0.309976,0.000000,0.309976,0.000000,0.000000,...,0.000000,0.000000,0.309976,0.197854,0.000000,0.000000,0.309976,0.000000,0.000000,0.309976
2,0.295059,0.000000,0.000000,0.000000,0.000000,0.000000,0.465256,0.000000,0.295059,0.000000,...,0.295059,0.000000,0.000000,0.000000,0.295059,0.295059,0.000000,0.295059,0.295059,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318256,0.000000,0.000000,0.403667,...,0.000000,0.403667,0.000000,0.257655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

As you can see from the output above, the TF-IDF scores are different than the scores obtained by the manual process we used earlier. This difference is due to sklearn's implementation of TF-IDF, which uses a slightly different formula. 


## Term Weighting

In a large text corpus, some words will be very present (e.g. “the”, “a”, “is” in English) hence carrying very little meaningful information about the actual contents of the document. If we were to feed the direct count data directly to a classifier those very frequent terms would shadow the frequencies of rarer yet more interesting terms.

In order to re-weight the count features into floating point values suitable for usage by a classifier it is very common to use the tf–idf transform.

Using the TfidfTransformer’s default settings, TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False) the term frequency, the number of times a term occurs in a given document, is multiplied with idf component, which is computed as 
$$
\text{idf}(t) = \log \left(\frac{1 + n}{1 + \text{df}(t)}\right) + 1
$$

where n is the total number of documents in the document set, and df(t) is the number of documents in the document set that contain term t. 
The resulting tf-idf vectors are then normalized by the Euclidean norm: 
$$
v_{\text{norm}} = \frac{v}{\|v\|_2} = \frac{v}{\sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}}
$$

This was originally a term weighting scheme developed for information retrieval (as a ranking function for search engines results) that has also found good use in document classification and clustering.

here the tf-idfs computed in scikit-learn’s TfidfTransformer and TfidfVectorizer differ slightly from the standard textbook notation that defines the idf as 

$$
\text{idf}(t) = \log \left(\frac{n}{1 + \text{df}(t)}\right)
$$
In the TfidfTransformer and TfidfVectorizer with smooth_idf=False, the “1” count is added to the idf instead of the idf’s denominator:

$$
\text{idf}(t) = \log \left(\frac{n}{\text{df}(t)}\right) +1
$$